# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [main]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0获取所有git提交历史记录，默认为1，1表示只获取最近的一次提交记录
      - name: Install pnpm
        uses: pnpm/action-setup@v4 # 如果使用 pnpm，请取消注释
        with:
          version: 9
      # - uses: oven-sh/setup-bun@v1 # 如果使用 Bun，请取消注释
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # 缓存管理器设置为npm
          cache: pnpm # 或 pnpm / yarn
      - name: 设置 GitHub Pages 的环境
        uses: actions/configure-pages@v4
      - name: 安装项目依赖
        # 运行命令行指令，这里使用npm ci表示的是check install,比传统的npm install更快
        run: pnpm install # 或 pnpm install / yarn install / bun install
      - name: 打包 vitePress
        # 运行vitePress中的构建指令
        run: pnpm docs:build # 或 pnpm docs:build / yarn docs:build / bun run docs:build
        # 将构建好的包上传为流水线的工件（artifact）
        timeout-minutes: 1 # 设置此步骤的超时时间为1分钟
        continue-on-error: true # 即使此步骤失败，也继续执行流水线
      - name: 上传 artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
